name: Lint the source 🧹
on: [push, pull_request]
jobs:
  test:
    name: Lint 🧹
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint
